# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftDemo' do
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'
end

target 'SwiftDemoTests' do

end

target 'SwiftDemoUITests' do

end

